server:
  port: 8880

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false     # gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router,这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: false     # 将请求路径上的服务名配置为小写
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI    # 大小写都可以
          predicates:       # 将以/demo/**开头的请求都会转发到uri对应的服务，使用routers时，需要将spring.cloud.gateway.discovery.locator.enabled改为false，否则会对同一个服务创建两个路由，不过两者都可以访问
            - Path=/demo/**
          filters:          # 用StripPrefix的filter 在转发之前将/demo去掉
            - StripPrefix=1
