server:
  port: 8771
eureka:
  client:
#    register-with-eureka: true  # \u5411eureka\u6CE8\u518C,\u9ED8\u8BA4true
#    fetch-registry: true  # \u4ECE\u670D\u52A1\u5668\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4true
    region: sc # \u6307\u5B9A\u81EA\u5B9A\u4E49region \u9ED8\u8BA4\u4E3Aus-east-l
    availability-zones: # \u6307\u5B9Aregion\u540E\uFF0C\u9700\u6307\u5B9A\uFF0C\u4F1A\u4ECEzones\u4E2D\u83B7\u53D6zone\uFF0C\u6839\u636Ezone\u4ECEurl\u4E2D\u83B7\u53D6\u7B2C\u4E00\u4E2A\u53EF\u7528\u7684\u670D\u52A1\u5668\u6CE8\u518C
      sc: cd1,cd2
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      cd1: http://localhost:8761/eureka/
      cd2: http://localhost:8762/eureka/
spring:
  application:
    name: service-hi