server:
  port: 8790

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/674728631/cloud-config-repo # 配置git仓库地址
          search-paths:   # 配置仓库路径
          username:     # 访问git仓库的用户名
          password:     # 访问git仓库的用户密码
      label: master   # 配置仓库的分支

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
